<?xml version="1.0"?>

<robot name="m2wr" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- inludes -->
    <xacro:include filename="$(find m2wr_description)/urdf/m2wr.gazebo" />
    <xacro:include filename="$(find m2wr_description)/urdf/wheel.xacro" />
    <xacro:include filename="$(find m2wr_description)/urdf/materials.xacro" />

    <!-- hyper parameters : camera -->
    <xacro:property name="camera_size" value="0.06"/>
    <xacro:property name="camera_origin_x" value="0.24"/>
    <xacro:property name="camera_origin_y" value="0"/>
    <xacro:property name="camera_origin_z" value="0.05"/>

    <xacro:macro name="default_inertial" params="mass">
        <inertial>
            <mass value="${mass}"/>
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
        </inertial>
    </xacro:macro>

    <!-- main body -->
    <link name="link_chassis">

        <!-- pose and inertial -->
        <pose>0 0 0.1 0 0 0</pose>
        <inertial>
            <mass value="5"/>
            <origin rpy="0 0 0" xyz="0 0 0.1"/>
            <inertia ixx="0.0395416666667" ixy="0" ixz="0" iyy="0.106208333333" iyz="0" izz="0.106208333333"/>
        </inertial>

        <!-- body -->
        <collision name="collision_chassis">
            <geometry>
                <box size="0.5 0.3 0.07"/>
            </geometry>
        </collision>

        <!-- visual -->
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0.0"/>
            <geometry>
                <box size="0.5 0.3 0.07"/>
            </geometry>
            <material name="orange"/>
        </visual>

        <!-- caster front -->
        <collision name="caster_front_collision">
            <origin rpy=" 0 0 0" xyz="0.35 0 -0.05"/>
            <geometry>
                <sphere radius="0.05"/>
            </geometry>
            <surface>
                <friction>
                    <!-- frictionless between these two surface -->
                    <ode>
                        <mu>0</mu>
                        <mu2>0</mu2>
                        <slip1>1.0</slip1>
                        <slip2>1.0</slip2>
                    </ode>
                </friction>
            </surface>
        </collision>
        <visual name="caster_front_visual">
            <origin rpy=" 0 0 0" xyz="0.2 0 -0.05"/>
            <geometry>
                <sphere radius="0.05"/>
            </geometry>
        </visual>

        <!-- caster back -->
        <collision name="caster_back_collision">
            <origin rpy=" 0 0 0" xyz="-0.35 0 -0.05"/>
            <geometry>
                <sphere radius="0.05"/>
            </geometry>
            <surface>
                <friction>
                    <!-- frictionless between these two surface -->
                    <ode>
                        <mu>0</mu>
                        <mu2>0</mu2>
                        <slip1>1.0</slip1>
                        <slip2>1.0</slip2>
                    </ode>
                </friction>
            </surface>
        </collision>
        <visual name="caster_back_visual">
            <origin rpy=" 0 0 0" xyz="-0.2 0 -0.05"/>
            <geometry>
                <sphere radius="0.05"/>
            </geometry>
        </visual>
    </link>

    <!-- sensor : link -->
    <link name="camera">
        <!-- visual -->
        <visual>
            <geometry>
                <box size="${camera_size/3} ${camera_size} ${camera_size/2}"/>
            </geometry>
        <material name="white"/>
        </visual>
        <!-- collsion -->
        <collision>
            <geometry>
                <box size="${camera_size/3} ${camera_size} ${camera_size/2}"/>
            </geometry>
        </collision>
        <xacro:default_inertial mass="0.02"/>
    </link>
    <!-- sensor : joint -->
    <joint name="camera_joint" type="fixed">
        <origin xyz="${camera_origin_x} ${camera_origin_y} ${camera_origin_z}" rpy="0 0 0"/>
        <parent link="link_chassis"/>
        <child link="camera"/>
    </joint>

    <!-- left and right wheels -->
    <xacro:link_wheel name="link_right_wheel" />
    <xacro:joint_wheel name="joint_right_wheel" child="link_right_wheel" origin_xyz="-0.05 0.20 0.0" />

    <xacro:link_wheel name="link_left_wheel" />
    <xacro:joint_wheel name="joint_left_wheel" child="link_left_wheel" origin_xyz="-0.05 -0.20 0.0" />


</robot>
